src/BaseBundle/Entity/Budget.php
<?php

namespace BaseBundle\Entity;

use BaseBundle\Entity\Traits\ArrayTrait;
use BaseBundle\Entity\Traits\Base;
use BaseBundle\Entity\Traits\BaseUUId;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Finder\Finder;

/**
 * Budget
 *
 * @ORM\Table(
 *     name="clinical_budget"
 * )
 * @ORM\Entity(repositoryClass="BaseBundle\Repository\BudgetRepository")
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Cache(usage="NONSTRICT_READ_WRITE", region="clinical_region")
 */
class Budget
{
    use BaseUUId;
    use ArrayTrait;
    const PAYMENT_CREDIT_CARD    = "credit_card";
    const PAYMENT_MONEY          = "money";
    const PAYMENT_TICKET         = "ticker";

    const STATUS_PENDIND           = NULL;
    const STATUS_APPROVED          = 1;
    const STATUS_DISAPPROVED       = 0;
    const STATUS_FINISHED          = 2 ;

    const PAYMENT_STATE_PAID       = 1;
    const PAYMENT_STATE_PENDING    = 0;

    /** @var array user friendly named type */
    protected static $paymentMethod = [
        self::PAYMENT_CREDIT_CARD    => 'clinical.user.quote.payment_credit_card',
        self::PAYMENT_MONEY => 'clinical.user.quote.payment_money',
        self::PAYMENT_TICKET => 'clinical.user.quote.payment_ticket'
    ];

    /** @var array user friendly named type */
    protected static $statusMethod = [
        self::STATUS_PENDIND    => 'clinical.user.quote.status.pending',
        self::STATUS_APPROVED => 'clinical.user.quote.status.approved',
        self::STATUS_DISAPPROVED => 'clinical.user.quote.status.disaproved',
        self::STATUS_FINISHED => 'clinical.user.quote.status.finished'
    ];


    /** @var array user friendly named type */
    protected static $paymentStateMethod = [
        self::PAYMENT_STATE_PENDING    => 'clinical.user.quote.status.pending',
        self::PAYMENT_STATE_PAID => 'clinical.user.quote.status.finished'
    ];
    /**
     * @return array<string>
     */
    public static function getPaymentMethods()
    {
        return [

            self::PAYMENT_CREDIT_CARD,
            self::PAYMENT_MONEY,
            self::PAYMENT_TICKET
        ];
    }

    /**
     * @return array<string>
     */
    public static function getPaymentStateMethods()
    {
        return [

            self::PAYMENT_STATE_PENDING,
            self::PAYMENT_STATE_PAID
        ];
    }
    /**
     * @return array<string>
     */
    public static function getStateMethods()
    {
        return [

            self::STATUS_PENDIND,
            self::STATUS_APPROVED,
            self::STATUS_DISAPPROVED,
            self::STATUS_FINISHED
        ];
    }

    /**
     * @return array<string>
     */
    public static function getThootElements()
    {
        $el = [];
        for ($i = 1; $i <= 32; $i++) {
           array_push($el,$i);
        }
        return $el;
    }

    /**
     * @param  string $paymentMethod
     * @return string
     */
    public static function getPaymentMethod($typeShortName)
    {
        if (!isset(static::$paymentMethod[$typeShortName])) {
            return "Unknown type ($typeShortName)";
        }

        return static::$paymentMethod[$typeShortName];
    }


    /**
     * @param  string $paymentMethod
     * @return string
     */
    public static function getStateMethod($typeShortName)
    {
        if (!isset(static::$statusMethod[$typeShortName])) {
            return "Unknown type ($typeShortName)";
        }

        return static::$statusMethod[$typeShortName];
    }


    /**
     * @var string pagamento
     * @ORM\Column(name="payment", type="string", nullable=true)
     */
    protected $payment;

    /**
     * @var \DateTime
     * @ORM\Column(name="validity", type="datetime", nullable=true)
     */
    protected $validity;

    /**
     * @var string  status(1=Aprovado, 0=reprovado, null = pendente de aprovacao
     *
     * @ORM\Column(name="status", type="boolean", nullable=true)
     */
    protected $status;

    /**
     * @var string  status(1= done,)
     *
     * @ORM\Column(name="done", type="boolean", nullable=true)
     */
    protected $done = 0;

    /**
     * @var string  status(1= done,)
     *
     * @ORM\Column(name="paid", type="boolean", nullable=true)
     */
    protected $paid = 0;


    /**
     * @var \DateTime
     * @ORM\Column(name="paid_date", type="datetime", nullable=true)
     *
     */
    protected $paid_date;

    /**
     * @var string - Dente
     *
     * @ORM\Column(name="tooth", type="integer", nullable=true)
     */
    protected $tooth;

    /**
     * @var string
     *
     * @ORM\Column(name="value", type="decimal", precision=7, scale=2)
     */
    protected $value = 0;

    /**
     * @var string
     *
     * @ORM\Column(name="total", type="decimal", precision=7, scale=2)
     */
    protected $total = 0;

    /**
     * @var string
     *
     * @ORM\Column(name="discount", type="integer", nullable=true)
     */
    protected $discount;

    /**
     * Convenio
     * @var \BaseBundle\Entity\Clinic
     *
     * @ORM\ManyToOne(targetEntity="BaseBundle\Entity\Agreement", fetch="EXTRA_LAZY")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="fk_agreement", referencedColumnName="id", onDelete="SET NULL")
     * })
     */
    protected $agreement;

    /**
     * Plano de tratamento
     * @var \BaseBundle\Entity\Clinic
     *
     * @ORM\OneToOne(targetEntity="BaseBundle\Entity\Plan",inversedBy="budget" ,fetch="EXTRA_LAZY", cascade={"all"})
     */
    protected $plan;

    /**
     * @var \BaseBundle\Entity\Clinic
     *
     * @ORM\ManyToOne(targetEntity="BaseBundle\Entity\Clinic",cascade={"all"},fetch="EXTRA_LAZY")
     */
    protected $clinic;

//    /**
//     * @var \BaseBundle\Entity\User
//     *
//     * @ORM\ManyToOne(targetEntity="BaseBundle\Entity\User",fetch="EXTRA_LAZY")
//     * @ORM\JoinColumns({
//     *   @ORM\JoinColumn(name="fk_professional", referencedColumnName="id", onDelete="SET NULL")
//     * })
//     */
//    protected $professional;

    /**
     * @var \BaseBundle\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="BaseBundle\Entity\User",fetch="EXTRA_LAZY")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="fk_created_by", referencedColumnName="id", onDelete="SET NULL")
     * })
     */
    protected $createdBy;

    /**
     * @var \BaseBundle\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="BaseBundle\Entity\User",fetch="EXTRA_LAZY")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="fk_client", referencedColumnName="id", onDelete="CASCADE")
     * })
     */
    protected $client;

    public function __construct()
    {
        $this->done = 0;
        $this->paid = 0;
        //$this->plan = new Plan();
    }

//    /**
//     * @param \BaseBundle\Entity\Procedure procedure
//     */
//    public function addProcedure(Procedure $procedure)
//    {
//        $this->getPlan()->addProcedure($procedure);
//    }
//
//    /**
//     * @param \BaseBundle\Entity\Procedure procedure
//     */
//    public function removeProcedure(Procedure $procedure)
//    {
//        $this->getPlan()->removeProcedure($procedure);
//    }

    /**
     * @return \BaseBundle\Entity\Procedure
     */
    public function getProcedures()
    {
        return $this->getPlan()->getProcedures();
    }

    /**
     * @return string
     */
    public function getTotal()
    {

        return $this->total;
    }


    /**
     * @param string $total
     * @return Budget
     *
     */
    public function setTotal()
    {

        $percentual = $this->getDiscount() / 100.0; // pega a porcentagem 0,15

        $this->total = $this->getValue() - ( $percentual * $this->getValue());

        return $this;
    }



    /**
     * @return string
     */
    public function getTooth()
    {
        return $this->tooth;
    }

    /**
     * @param string $tooth
     * @return Budget
     */
    public function setTooth($tooth)
    {
        $this->tooth = $tooth;
        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * @param string $value
     * @return Budget
     */
    public function setValue($value)
    {
        $this->value = $value;
        $this->setTotal();

        return $this;
    }

    /**
     * @return string
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    /**
     * @param string $discount
     * @return Budget
     */
    public function setDiscount($discount)
    {
        $this->discount = $discount;
        return $this;
    }

    /**
     * @return Clinic
     */
    public function getAgreement()
    {
        return $this->agreement;
    }

    /**
     * @param Clinic $agreement
     * @return Budget
     */
    public function setAgreement($agreement)
    {
        $this->agreement = $agreement;
        return $this;
    }

    /**
     * @return Plan
     */
    public function getPlan()
    {
        return $this->plan;
    }

    /**
     * @param Clinic $plan
     * @return Budget
     */
    public function setPlan($plan)
    {
        $this->plan = $plan;
        return $this;
    }



    /**
     * @return string
     */
    public function getPayment()
    {
        return $this->payment;
    }

    /**
     * @param string $payment
     * @return Budget
     */
    public function setPayment($payment)
    {
        $this->payment = $payment;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getValidity()
    {
        return $this->validity;
    }

    /**
     * @param \DateTime $validity
     * @return Budget
     */
    public function setValidity(\DateTime $validity): Budget
    {
        $this->validity = $validity;
        return $this;
    }

    /**
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param string $status
     * @return Budget
     */

src/BaseBundle/Entity/Procedure.php
<?php

namespace BaseBundle\Entity;

use BaseBundle\Entity\Traits\ArrayTrait;
use BaseBundle\Entity\Traits\Base;
use BaseBundle\Entity\Traits\BaseUUId;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Procedure
 *
 * @ORM\Table(
 *     name="clinical_procedure"
 * )
 * @ORM\Entity(repositoryClass="BaseBundle\Repository\ProcedureRepository")
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Cache(usage="NONSTRICT_READ_WRITE", region="clinical_region")
 */
class Procedure
{
    public function __toString()
    {
        return (string) $this->getDescription();
    }
    use BaseUUId;
    use ArrayTrait;

    /**
     * @var string
     *
     * @ORM\Column(name="description",type="text", nullable=true)
     * @Assert\NotBlank()
     */
    protected $description;

    /**
     * @var string
     *
     * @ORM\Column(name="color",type="string", nullable=true)
     */
    protected $color;

    /**
     * @var string
     *
     * @ORM\Column(name="average_time",type="integer", nullable=true)
     */
    protected $average_time;

    /**
     * @var PlanProcedure $procedures
     *
     * @ORM\OneToMany(targetEntity="BaseBundle\Entity\PlanProcedure", mappedBy="procedure",fetch="EXTRA_LAZY")
     */
    protected $procedures;

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return Procedure
     */
    public function setDescription($description)
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @return string
     */
    public function getAverageTime()
    {
        return $this->average_time;
    }

    /**
     * @param string $average_time
     * @return Procedure
     */
    public function setAverageTime($average_time)
    {
        $this->average_time = $average_time;
        return $this;
    }

    /**
     * @return PlanProcedure
     */
    public function getProcedures(): PlanProcedure
    {
        return $this->procedures;
    }

    /**
     * @param PlanProcedure $procedures
     * @return Procedure
     */
    public function setProcedures(PlanProcedure $procedures): Procedure
    {
        $this->procedures = $procedures;
        return $this;
    }

    /**
     * @return string
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * @param string $color
     * @return Procedure
     */
    public function setColor($color)
    {
        $this->color = $color;
        return $this;
    }




}

src/BaseBundle/Controller/UserController.php
<?php

namespace BaseBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends Controller
{

    /**
     * @Route("/user/area", name="user")
     * @Template("BaseBundle:Default:index.html.twig")
     */
    public function indexAction()
    {
        $roles = $this->getUser();
        return  ["roles" => $roles->getRoles()];
    }
}

templates/doctor/clinic/user/budget/user-budget-child-list.html.twig
<tr class="m-datatable__row m-datatable__row--even m-datatable__row-detail" data-value="{{ budget.id }}" style="display: none">
    <td class="m-datatable__detail" colspan="6">
        <div id="child_data_local_{{ budget.id }}">

            <div class="m-portlet__body  m-portlet__body--no-padding" >
                <div class="row m-row--no-padding m-row--col-separator-xl">
                    <div class="col-md-12 col-lg-6 col-xl-3">
                        <!--begin::Total Profit-->
                        <div class="m-widget24 table-responsive">
                            <table class="table table-sm table-striped table-condensed">
                                <thead>


                                {#<tr class="m-datatable__row m-datatable__row--even">#}
                                    {#<th>#}
                                        {#{{ 'clinic.label.budget.profissional'|trans }}#}

                                    {#</th>#}
                                    {#<td>#}
                                        {#<span class="pull-right">{{ budget.professional.name |e  }}</span>#}
                                    {#</td>#}
                                {#</tr>#}
                                <tr class="m-datatable__row m-datatable__row--even">
                                    <th>
                                        {{ 'clinic.label.budget.created_by'|trans }}
                                    </th>
                                    <td>
                                        <span class="pull-right">{{ budget.createdBy.name |e  }}</span>
                                    </td>
                                </tr>
                                <tr class="m-datatable__row m-datatable__row--even">

                                        <th>
                                            {{ 'clinic.label.budget.agreement'|trans }}
                                        </th>

                                        <td>{% if budget.agreement %}
                                            <span class="pull-right">{{ budget.agreement.fantasia |e  }}</span>
                                            {% endif %}
                                        </td>



                                </tr>

                                <tr class="m-datatable__row m-datatable__row--even">
                                    <th>
                                        {{ 'clinic.label.budget.validity'|trans }}
                                    </th>
                                    <td>

                                        <span class="pull-right">   {{ budget.validity |date('d/m/Y')  }}</span>
                                    </td>
                                </tr>

                                <tr class="m-datatable__row m-datatable__row--even">
                                    <th>
                                        {{ 'clinic.label.budget.tooth'|trans }}
                                    </th>
                                    <td>
                                        <span style="font-weight: bold"> {{ budget.tooth |e  }}</span>
                                    </td>
                                </tr>

                                <tr class="m-datatable__row m-datatable__row--even">
                                    <th>
                                        {% if  budget.done == true %}
                                            Data de execução
                                        {% else %}
                                            {{ 'clinic.label.budget.status'|trans }}
                                        {% endif %}
                                    </th>
                                    <td>
                                        {% if  budget.done == true %}

                                            <span class="pull-right">   {{ budget.paiddate|date('d/m/Y H:i') }} </span>
                                        {% else %}
                                            {%  if budget.status is null and budget.isValid == false %}
                                                <span class="pull-right"> Vencido </span>

                                            {% else %}
                                                <span class="pull-right"> {{ budget.getStateMethod(budget.status) |trans }}</span>
                                            {% endif %}
                                        {% endif %}
                                    </td>
                                </tr>
                                </thead>
                            </table>
                        </div>
                        <!--end::Total Profit-->
                    </div>
                    <div class="col-md-12 col-lg-6 col-xl-3">
                        <!--begin::New Feedbacks-->
                        <div class="m-widget24 table-responsive">
                            <table class="table table-sm table-striped">
                                <thead>

                                <tr class="m-datatable__row m-datatable__row--even">
                                    <th>
                                        {{ 'clinic.label.budget.value'|trans }}
                                    </th>
                                    <td>
                                        <span class="pull-right"> R$ {{ budget.value |e  }}</span>
                                    </td>
                                </tr>
                                <tr class="m-datatable__row m-datatable__row--even">
                                    <th>
                                        {{ 'clinic.label.budget.discount'|trans }}(%)
                                    </th>
                                    <td>
                                        <span class="pull-right">   {{ budget.discount |e  }}</span>

                                    </td>
                                </tr>
                                <tr class="m-datatable__row m-datatable__row--even">
                                    <th>
                                        {{ 'clinic.label.budget.total'|trans }}
                                    </th>
                                    <td>
                                        <span class="pull-right">  R$ {{ budget.total |e  }}</span>
                                    </td>
                                </tr>

                                <tr class="m-datatable__row m-datatable__row--even">
                                    <th>
                                        {{ 'clinic.label.budget.payment_method'|trans }}
                                    </th>
                                    <td>
                                        <span class="pull-right">  {{ budget.getPaymentMethod(budget.payment) |trans  }}</span>

                                    </td>
                                </tr>


                                <tr class="m-datatable__row m-datatable__row--even">
                                    <th>
                                        Pagamento
                                    </th>
                                    <td>
                                        {% if budget.paid == true %}
                                            <span class="pull-right">   {{ budget.paiddate|date('d/m/Y H:i') }} </span>
                                        {% else %}
                                            <span class="pull-right">  Pendente </span>
                                        {% endif %}

                                    </td>
                                </tr>



                                </thead>
                            </table>
                        </div>
                        <!--end::New Feedbacks-->
                    </div>

                    <div class="col-md-12 col-lg-6 col-xl-6">
                        <!--begin::New Orders-->
                        <div class="m-widget24 table-responsive">
                            <table class="table table-sm table-striped">
                                <thead>

                                <tr class="m-datatable__row m-datatable__row--even">
                                    <th>
                                        {{ 'clinic.label.budget.plan.details'|trans }}
                                    </th>
                                    <td>
                                        <span class="pull-right">  {{ budget.plan.details |e  }}</span>
                                    </td>
                                </tr>
                                <tr class="m-datatable__row m-datatable__row--even">
                                    <th>
                                        {{ 'clinic.label.budget.profissional'|trans }}
                                    </th>
                                    <td>
                                        <span class="pull-right">  {{ budget.plan.professional.name |e  }}</span>
                                    </td>
                                </tr>
                                    {#<tr class="m-datatable__row m-datatable__row--even">#}
                                        {#<th>#}
                                            {#{{ 'clinic.label.budget.plan.procedures.data'|trans }}#}
                                        {#</th>#}
                                        {#<td>#}
                                            {#<span class="pull-right"> {{ budget.plan.date |date('d/m/Y H:i')  }}</span>#}

                                        {#</td>#}
                                    {#</tr>#}

                                <tr class="m-datatable__row">
                                    <td>

                                        <span class="pull-left" style="width: 60%"> {{ 'clinic.label.budget.plan.procedures'|trans }}</span>

                                        <span class="center"style="width: 10%">Tempo</span>
                                        <span class="pull-right" style="width: 30%"> Data de execução</span>
                                    </td>

                                </tr>

                                {% for procedures in  budget.plan.procedures %}
                                    {% set procedure = procedures.procedure %}
                                    <tr class="m-datatable__row m-datatable__row--even">

                                        <td style="width: 60%">
                                            <p style="font-size: 11pt; font-style:italic">
                                            {{ procedure.description |e  }}
                                            </p>

                                        </td>
                                        <td style="width: 10%">
                                            <span class="m-widget4__info-date m--font-info" style="font-size: 12pt; font-weight: ligther;">
                                            {{ procedure.averageTime |e  }} Hr(s)
                                            </span>
                                        </td>
                                        <td style="width: 30%">
                                            <span class="m-widget4__info-date m--font-info" style="font-size: 12pt; font-weight: ligther;">
                                            {{ procedures.date|date('d/m/Y H:i') }}
                                            </span>
                                        </td>
                                    </tr>

                                    {#<div class="m-widget5__item">#}

                                        {#<div class="media-body pull-left">#}
                                            {#<p class="m-widget4__text" style="width: 90%">#}
                                                {#{{ procedure.description |e  }}#}
                                            {#</p>#}
                                        {#</div>#}
                                        {#<div class="m-widget4__ext pull-right">#}
                                                    {#<span class="m-widget4__info-date m--font-info" style="font-size: 12pt; ">#}
                                                        {#{{ procedure.averageTime |e  }} Hr(s)#}
                                                    {#</span>#}
                                        {#</div>#}
                                    {#</div>#}

                                {% else %}
                                    <center><b>{{ 'clinic.label.not_found'|trans }}</b></center>
                                {% endfor %}




                                </thead>
                            </table>
                        </div>
                        <!--end::New Orders-->
                    </div>

                </div>

        </div>

            <hr>
    </td>
</tr>

templates/doctor/clinic/user/budget/user-budget.html.twig
{% extends 'layouts/doctor.html.twig' %}


{% block main_content %}
    <div class="col-xl-12 col-lg-12">
        <div class="m-portlet m-portlet--tabs {%  if user.enabled ==false %} m-portlet--danger {% else %} m-portlet--success {% endif %}  m-portlet--head-solid-bg m-portlet--bordered">

            {% include 'doctor/clinic/user/user-tab.html.twig' with {'active': 'quote'} %}
            <div class="m-portlet__body">
                <div class="tab-content">

                    {% include 'doctor/clinic/user/budget/user-budget-list.html.twig'%}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block custom_javascripts %}
    <script>

        jQuery(document).ready(function() {

            $(".m-datatable__toggle-subtable").click(function(){

                el_right = $(this).find(".fa-caret-right");
                el_down = $(this).find(".fa-caret-down");
                var primaryKey = $(this).data('value');
                if($(el_right).hasClass("fa-caret-right")){

                    $(el_right).removeClass('fa-caret-right').addClass('fa-caret-down');

                    el_detail = $(".m-datatable__row-detail").filter('[data-value="'+ primaryKey+'"]');

                    $(el_detail).show();

                } else if ($(el_down).hasClass("fa-caret-down")){

                    $(el_down).removeClass('fa-caret-down').addClass('fa-caret-right');
                    el_detail = $(".m-datatable__row-detail").filter('[data-value="'+ primaryKey+'"]');
                    $(el_detail).hide();
                }


            });

        });
    </script>
{% endblock %}

templates/doctor/clinic/user/budget/user-procedure.html.twig
{% extends 'layouts/doctor.html.twig' %}


{% block main_content %}
    <div class="col-xl-12 col-lg-12">
        <div class="m-portlet m-portlet--tabs {%  if user.enabled ==false %} m-portlet--danger {% else %} m-portlet--success {% endif %}  m-portlet--head-solid-bg m-portlet--bordered">

            {% include 'doctor/clinic/user/user-tab.html.twig' with {'active': 'procedure'} %}
            <div class="m-portlet__body">
                <div class="tab-content">

                </div>
            </div>
        </div>
    </div>

{% endblock %}